/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/
#include "project.h"

#define LEDON 0
#define LEDOFF 1

typedef enum{ red, green, blue, yellow, magenta, cyan, white, black } color;

void StackEventHandler(uint32 event, void *eventParam);
void setLedColor(color x);
CYBLE_GATT_ERR_CODE_T updateIsConfigPresent(uint8 newValue);

int bleConnected = 0;
int writeEventOccured = 0;
CYBLE_CONN_HANDLE_T connectionHandle;

//SAHWD variables
uint8 isConfigPresent = 1;
uint8 configClearRequestByCLient = 0;

int main(void)
{
    CYBLE_API_RESULT_T apiResult;
    
    CyGlobalIntEnable; /* Enable global interrupts. */

    /* Place your initialization/startup code here (e.g. MyInst_Start()) */
    SERIAL_Start();
    SERIAL_PutString("PSoC BLE Custom Service\r\n");
    setLedColor(red);
    CyDelay(500);
    setLedColor(green);
    CyDelay(500);
    setLedColor(blue);
    CyDelay(500);
    setLedColor(yellow);
    CyDelay(500);
    setLedColor(magenta);
    CyDelay(500);
    setLedColor(cyan);
    CyDelay(500);
    setLedColor(white);
    CyDelay(500);
    
    apiResult = CyBle_Start(StackEventHandler);

    if(apiResult != CYBLE_ERROR_OK)
    {
        /* BLE stack initialization failed, check your configuration */
        CYASSERT(0);
    }
    
    //DEBUG
    updateIsConfigPresent(0x69);

    for(;;)
    {    
        CyBle_ProcessEvents();
        if(bleConnected)
        {
            if(configClearRequestByCLient && bleConnected && isConfigPresent)
            {
                isConfigPresent = 0;
                //TODO CLEAR CONFIG
                if(updateIsConfigPresent(isConfigPresent) == CYBLE_GATT_ERR_NONE)
                {
                    
                    SERIAL_PutString("CLEARING CONFIG\r\n");
                }
                
            }
        }
    }
}

void StackEventHandler(uint32 event, void *eventParam)
{
    CYBLE_GATTS_WRITE_CMD_REQ_PARAM_T *wrReq;
    CYBLE_GATTS_WRITE_REQ_PARAM_T *wrReqParam;
    CYBLE_GATTS_READ_RSP_PARAM_T *rdRspParam;
    switch(event)
    {
        /* Mandatory events to be handled by Find Me Target design */
        case CYBLE_EVT_STACK_ON:
        case CYBLE_EVT_GAP_DEVICE_DISCONNECTED:
            SERIAL_PutString("BLE Disconnected\r\n");
            /* Start BLE advertisement for 30 seconds and update link
             * status on LEDs */
            bleConnected = 0;
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            break;

        case CYBLE_EVT_GAP_DEVICE_CONNECTED:
            /* BLE link is established */
            SERIAL_PutString("BLE Connected\r\n");
            bleConnected = 1;
            break;
        case CYBLE_EVT_GATTS_WRITE_REQ:
            SERIAL_PutString("BLE Write Event\r\n");
            
            /* Extract the Write data sent by Client */
            wrReqParam = (CYBLE_GATTS_WRITE_REQ_PARAM_T *) eventParam;
            if(CYBLE_CLEARCONFIG_CUSTOM_CHARACTERISTIC_CHAR_HANDLE == wrReqParam->handleValPair.attrHandle)
            {
                if( *(wrReqParam->handleValPair.value.val) == 1)
                {
                    configClearRequestByCLient = 1;
                }
            }
            //CyBle_GattsWriteRsp(connectionHandle);
            (void)CyBle_GattsWriteRsp(((CYBLE_GATTS_WRITE_REQ_PARAM_T *)eventParam)->connHandle);
            break;
        case CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP:
            if(CyBle_GetState() == CYBLE_STATE_DISCONNECTED)
            {
                /* Advertisement event timed out, go to low power
                 * mode (Stop mode) and wait for device reset
                 * event to wake up the device again */
                CySysPmSetWakeupPolarity(CY_PM_STOP_WAKEUP_ACTIVE_HIGH);
                CySysPmStop();
               
                /* Code execution will not reach here */
            }
            break;

        /* Other events that are generated by the BLE Component that
         * are not required for functioning of this design */
        /**********************************************************
        *                       General Events
        ***********************************************************/
        case CYBLE_EVT_HARDWARE_ERROR:    /* This event indicates that some internal HW error has occurred. */
            break;

        case CYBLE_EVT_HCI_STATUS:
            break;

        /**********************************************************
        *                       GAP Events
        ***********************************************************/
        case CYBLE_EVT_GAP_AUTH_REQ:
            break;

        case CYBLE_EVT_GAP_PASSKEY_ENTRY_REQUEST:
            break;

        case CYBLE_EVT_GAP_PASSKEY_DISPLAY_REQUEST:
            break;

        case CYBLE_EVT_GAP_AUTH_COMPLETE:

            break;
        case CYBLE_EVT_GAP_AUTH_FAILED:

            break;

        case CYBLE_EVT_GAP_ENCRYPT_CHANGE:
            break;

        case CYBLE_EVT_GAPC_CONNECTION_UPDATE_COMPLETE:
            break;

        /**********************************************************
        *                       GATT Events
        ***********************************************************/
        case CYBLE_EVT_GATT_CONNECT_IND:
            break;

        case CYBLE_EVT_GATT_DISCONNECT_IND:
            break;

        case CYBLE_EVT_GATTS_XCNHG_MTU_REQ:
            break;

        case CYBLE_EVT_GATTS_READ_CHAR_VAL_ACCESS_REQ:
            SERIAL_PutString("BLE read Event\r\n");

            break;

        /**********************************************************
        *                       Other Events
        ***********************************************************/
        case CYBLE_EVT_PENDING_FLASH_WRITE:
            break;

        default:
            break;
    }
}

void setLedColor(color x)
{
    // red, green, blue, yellow, magenta, cyan, white, black 
    switch(x)
    {
        case red:
            LED_RED_Write(LEDON);
            LED_GREEN_Write(LEDOFF);
            LED_BLUE_Write(LEDOFF);
            break;
        case green:
            LED_RED_Write(LEDOFF);
            LED_GREEN_Write(LEDON);
            LED_BLUE_Write(LEDOFF);
            break;
        case blue:
            LED_RED_Write(LEDOFF);
            LED_GREEN_Write(LEDOFF);
            LED_BLUE_Write(LEDON);
            break;
       case yellow:
            LED_RED_Write(LEDON);
            LED_GREEN_Write(LEDON);
            LED_BLUE_Write(LEDOFF);
            break;
       case magenta:
            LED_RED_Write(LEDON);
            LED_GREEN_Write(LEDOFF);
            LED_BLUE_Write(LEDON);
            break;  
       case cyan:
            LED_RED_Write(LEDOFF);
            LED_GREEN_Write(LEDON);
            LED_BLUE_Write(LEDON);
            break;             
       case white:
            LED_RED_Write(LEDON);
            LED_GREEN_Write(LEDON);
            LED_BLUE_Write(LEDON);
            break;  
       case black:
            LED_RED_Write(LEDOFF);
            LED_GREEN_Write(LEDOFF);
            LED_BLUE_Write(LEDOFF);
            break;              
        default:
        break;
    }
}

CYBLE_GATT_ERR_CODE_T updateIsConfigPresent(uint8 newValue)
{
    CYBLE_GATT_ERR_CODE_T apiGattErrCode = 0;
    
    CYBLE_GATT_HANDLE_VALUE_PAIR_T myHandle;
    myHandle.attrHandle = CYBLE_ISCONFIGPRESENT_CUSTOM_CHARACTERISTIC_CHAR_HANDLE; /* Attribute Handle of the characteristic in GATT Database*/
    myHandle.value.val = &newValue; /*Array where you want to store the data*/
    myHandle.value.len = sizeof(newValue); /* Length of data*/
    apiGattErrCode = CyBle_GattsWriteAttributeValue(&myHandle, 0, &cyBle_connHandle, CYBLE_GATT_DB_LOCALLY_INITIATED);
    return apiGattErrCode;
}

/* [] END OF FILE */
